SELECT COUNT(*),
  FROM_UNIXTIME(DATE, '%c') as MONTH,
  FROM_UNIXTIME(DATE, '%Y') as YEAR,
  CITY
FROM birth_report
WHERE CITY = "Locarno"
GROUP BY MONTH, YEAR
HAVING MONTH = 6 AND YEAR = 1988;